### ISSUE TITLE
Can't validate multiple Objects in a Single Manifest

### ISSUE THREAD

**Issue by philippe-granet** [kubernetes-sigs/kubectl-validate#123]
### What happened?

I can't validate multiple Objects in a Single Manifest

### What did you expect to happen?

It should fail if one of the objects in a manifest file is invalid

### How can we reproduce it (as minimally and precisely as possible)?

Using a `manifest.yaml` file with multiple Objects:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: validkind

---
apiVersion: v1
kind: configmap
metadata:
  name: invalidkind
```

and running `kubectl-validate manifest.yaml`, it return:
```
manifest.yaml...OK
```

but it should fail with this error message:
```
manifest.yaml...ERROR
failed to retrieve validator: kind configmap not found in v1 groupversion
Error: validation failed
```

### Kubernetes version

<details>

Using kubectl-validate 0.0.3

</details>
