### ISSUE TITLE
kind List not found in v1 groupversion

### ISSUE THREAD

**Issue by jplitza** [kubernetes-sigs/kubectl-validate#148]
### What happened?

Validating a manifest containing a List failed with the error message:
```
failed to retrieve validator: kind List not found in v1 groupversion
```

### What did you expect to happen?

I expect validation to succeed for every manifest I can apply without errors via `kubectl create -f`. Since Lists are understood by `kubectl create`, I expect them to be understood by kubectl validate.

### How can we reproduce it (as minimally and precisely as possible)?

Minimal (`kubectl create` complains there is nothing to apply, though):

```yaml
apiVersion: v1
kind: List
items: []
```

A bit more extensive (actually works with `kubectl create`):

```yaml
apiVersion: v1
metadata:
  namespace: default
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: test
  data:
    test: "foo"
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.30.4
```

kubectl-validate v0.0.4

</details>
