### ISSUE TITLE
int64 must be of type int-or-string

### ISSUE THREAD

**Issue by jplitza** [kubernetes-sigs/kubectl-validate#95]
### What happened?

I validated a [Calico network policy](https://docs.tigera.io/calico/latest/reference/resources/networkpolicy) that is successfully loaded in the cluster, and it reported:
```
NetworkPolicy.projectcalico.org "testcase-int-or-string" is invalid: spec.egress[0].destination.ports[0]: Invalid value: "int64": spec.egress[0].destination.ports[0] in body must be of type int-or-string: "int64"
```

### What did you expect to happen?

No validation errors.

### How can we reproduce it (as minimally and precisely as possible)?

Validate the following resource with the [Calico CRDs](https://github.com/projectcalico/calico/blob/v3.27.0/manifests/crds.yaml) referenced with `--local-crds`:
```yaml
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: testcase-int-or-string
  namespace: default
spec:
  egress:
    - action: Allow
      destination:
        namespaceSelector: kubernetes.io/metadata.name == "kube-system"
        selector: app.kubernetes.io/name == "coredns"
        ports:
         - 53
      protocol: UDP
      source: {}
```

### Anything else we need to know?

It works when the port is specified as string instead of number.

The relevant part of the CRD:
```yaml
                        ports:
                          description: "[...]"
                          items:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^.*
                            x-kubernetes-int-or-string: true
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

</details>
