### ISSUE TITLE
Better support for Kustomize

### ISSUE THREAD

**Issue by devantler** [kubernetes-sigs/kubectl-validate#96]
### What would you like to be added?

I am unable to make it work with Kustomize when running it against my running cluster. I would expect the validation to use the CRD from the cluster, but it seems there are no OpenAPI spec for Kustomize yet.

<img width="702" alt="image" src="https://github.com/kubernetes-sigs/kubectl-validate/assets/26203420/329f6a29-77dd-42e4-a5d9-223916829452">

Furthermore, it would be neat with some way to default to whitelisting/ignoring patches (maybe be checking the file name), such that patches do not fail because they do not follow the full spec. For example, this patch that adds a GHCR secret to the Flux HelmRelease, and allows it to use the host network:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set
  namespace: gha-runner-scale-set
spec:
  values:
    template:
      spec:
        imagePullSecrets:
          - name: ghcr-auth
        hostNetwork: true
```

<img width="916" alt="image" src="https://github.com/kubernetes-sigs/kubectl-validate/assets/26203420/cdff54ed-d6ba-45c8-bfc8-d39ff34c27b6">

### Why is this needed?

I would expect Kustomize to work out-of-the-box, or with little configuration, as it is quite commonly used in GitOps to deploy components, and to patch some manifest.
